# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcmicro.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpcmicro.proto\x12\tgrpcmicro\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"\'\n\x05Todos\x12\x1e\n\x05todos\x18\x01 \x03(\x0b\x32\x0f.grpcmicro.Todo\"\x07\n\x05\x45mpty2?\n\x0bTodoService\x12\x30\n\x08GetTodos\x12\x10.grpcmicro.Empty\x1a\x10.grpcmicro.Todos\"\x00\x42\"Z github.com/fingerprint/grpcmicrob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcmicro_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/fingerprint/grpcmicro'
  _globals['_TODO']._serialized_start=30
  _globals['_TODO']._serialized_end=82
  _globals['_TODOS']._serialized_start=84
  _globals['_TODOS']._serialized_end=123
  _globals['_EMPTY']._serialized_start=125
  _globals['_EMPTY']._serialized_end=132
  _globals['_TODOSERVICE']._serialized_start=134
  _globals['_TODOSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
