// Code generated by "stringer -type=UserRole,UploadMode,ScanMode"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUPERADMIN-1]
	_ = x[ADMIN-2]
	_ = x[USER-3]
}

const _UserRole_name = "SUPERADMINADMINUSER"

var _UserRole_index = [...]uint8{0, 10, 15, 19}

func (i UserRole) String() string {
	i -= 1
	if i < 0 || i >= UserRole(len(_UserRole_index)-1) {
		return "UserRole(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserRole_name[_UserRole_index[i]:_UserRole_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SURVEY_SUPERVISED-1]
	_ = x[SURVEY_UNSUPERVISED-2]
	_ = x[PREDICTION_TRIAL-3]
	_ = x[PREDICTION_TESTING-4]
	_ = x[PREDICTION_TRACKING-5]
}

const _UploadMode_name = "SURVEY_SUPERVISEDSURVEY_UNSUPERVISEDPREDICTION_TRIALPREDICTION_TESTINGPREDICTION_TRACKING"

var _UploadMode_index = [...]uint8{0, 17, 36, 52, 70, 89}

func (i UploadMode) String() string {
	i -= 1
	if i < 0 || i >= UploadMode(len(_UploadMode_index)-1) {
		return "UploadMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UploadMode_name[_UploadMode_index[i]:_UploadMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTERVAL-1]
	_ = x[SINGLE-2]
}

const _ScanMode_name = "INTERVALSINGLE"

var _ScanMode_index = [...]uint8{0, 8, 14}

func (i ScanMode) String() string {
	i -= 1
	if i < 0 || i >= ScanMode(len(_ScanMode_index)-1) {
		return "ScanMode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ScanMode_name[_ScanMode_index[i]:_ScanMode_index[i+1]]
}
