version: '3.9'

services:
  postgres:
    container_name: postgres-fp
    image: postgres:15.3-alpine
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - fp2_vol:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    networks:
      - fp2_net
    restart: always
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./db/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER= ${MINIO_USER}
      - MINIO_ROOT_PASSWORD= ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    networks:
      - fp2_net
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-fp
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    volumes:
      - pgadmin_fp2_data:/var/lib/pgadmin
    env_file:
      - ./.env
    networks:
      - fp2_net

volumes:
  fp2_vol:
    external: false
  minio_data:
    driver: local
    external: false
  pgadmin_fp2_data:
    external: false

networks:
  fp2_net:
    driver: bridge
    external: false
