info:
  contact: {}
  description: This is a sample swagger for Fiber
  title: API Documentation
  version: "0.2"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
